Escape emoji that are interpreted as Regex expressions
One or all of these emoji #⃣ #️⃣ *⃣ were causing:
== Compilation error on file lib/exmoji/scanner.ex ==
** (Regex.CompileError) nothing to repeat at position 5795
    (elixir) lib/regex.ex:142: Regex.compile!/2
    lib/exmoji/scanner.ex:43: (module)
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6